name: Build and Publish Helm Chart

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Package Helm chart
        run: |
          helm package ./helm/ozzyto-streamer --destination ./helm-packages

      - name: Set up chart repository
        if: github.event_name != 'pull_request'
        run: |
          helm repo index ./helm-packages --url https://github.com/${{ github.repository }}/releases/download/helm-chart

      - name: Get chart version
        id: chart_version
        run: |
          VERSION=$(grep 'version:' ./helm/ozzyto-streamer/Chart.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload Helm chart as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: ./helm-packages

      - name: Create GitHub Release for Helm Chart
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./helm-packages/*
          tag_name: helm-chart-${{ steps.chart_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true